//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char smiley_bmp_test [] = {
0x00, 0x84, 0x84, 0x00, 0x00, 0x84, 0x78, 0x00, 
};
